### ISSUE TITLE
test if it is feasible to switch to JSTransformers

### ISSUE THREAD

**Issue by doodzik** [superwolff/metalsmith-layouts#102]
ref: #100 

test JSTransformers for speed and reliability against the test suite.

we probably need a benchmark test

**Comment by ismay** [comment]
After thinking about I think that we should definitely give the transition to jstransformers a try. Unfortunately I've still not got a lot of time atm to work on this, but I might have in the near future. Until then I'll try and make some sketches for benchmarking and the implementation of jstransformers. I'll let you know when I have something up.

**Comment by doodzik** [comment]
sounds good 👍

**Comment by doodzik** [comment]
see in-place
