### ISSUE TITLE
Passing `filename` to jade

### ISSUE THREAD

**Issue by rstacruz** [superwolff/metalsmith-layouts#14]
Using includes and extends in jade is not supported because it needs the `filename` option passed onto `jade.compile()`. is there a sane solution to this -- maybe bypass `consolidate` for jade?

```jade
/ layouts/default.jade
html
  include ../partials/menu.jade
  != contents
```

```
Error: the "filename" option is required to use "include" with "relative" paths
```

I'd be happy to prepare a PR if you'd like.

**Comment by rstacruz** [comment]
another option is to simply add `"filename": "/path/to/layouts/default.jade"` to the local variables, which should be reasonable data to include anyway.

the way `consolidate` works is that locals are also passed as jade options: https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L339

**Comment by ismay** [comment]
Basically this plugin just wraps consolidate, so I don't think bypassing consolidate is an option. So what does jade need exactly? The filename of the filename of the `layout` that's been selected in the front-matter?

**Comment by rstacruz** [comment]
I believe it needs to know the filename and its abs path:

```js
consolidate.jade('...template data...', { filename: '/path/to/source.jade' })
```

not sure on the `omit` thing yet, lemme take some time to sit down and grok that :)

**Comment by ismay** [comment]
Moox to the rescue again: [metalsmith-filenames](https://github.com/MoOx/metalsmith-filenames/). Let me know if this fixes it. I'll do some testing myself as well.

**Comment by ismay** [comment]
After some testing, metalsmith-filenames solves this for me. Closing, but let me know if it doesn't solve it for you or you have other questions.
