### ISSUE TITLE
Expose consolidate.requires

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-layouts#18]
To allow for template engine instances to be configured and passed to consolidate.

See: https://github.com/superwolff/metalsmith-layouts/issues/6

**Comment by ismay** [comment]
@Rowno, @grancalavera In #6 the use of `consolidate.requires` came up as a way to configure templating engines. I'm working on a way to allow access to the `requires` method with `metalsmith-layouts`, and was wondering whether you've encountered any engines that can't be configured globally.

Because apparently swig, nunjucks and handlebars can all be configured globally, so reliably testing for this would require an engine that can't.

**Comment by Rowno** [comment]
Hmmm, not sure.

**Comment by ismay** [comment]
I'll just keep this open for now. If someone encounters something that can't be configured with a global instance, they can report it here.

**Comment by grancalavera** [comment]
@ismay @Rowno I think the main issue is that sometimes you want to have more than one renderer. In small websites this will probably not happen, and having a single globally configured templating engine should be enough. But there are cases when it might be preferable to separate helpers, or contexts, or even create them dynamically. 

In that sense, being able to configure the templating engine instance directly would make sense to me. Also, that would also cater for the case where a given templating engine cannot be configured globally.
