### ISSUE TITLE
Rendering Template tags in template and layout

### ISSUE THREAD

**Issue by iansoper** [superwolff/metalsmith-layouts#27]
I would like to be able to render templates tags in both the template and the layout. Is there a way to do this or will they only render in the layout?

**Comment by iansoper** [comment]
I just read this on the [metalsmith-in-place readme](https://github.com/superwolff/metalsmith-in-place):
> A more advanced use of this plugin would be extending templates or __combining the use of templating syntax in your source files with layouts.__

Can you explain how to do this?

**Comment by ismay** [comment]
Of course! Basically `metalsmith-in-place` will render any syntax in the template, and `metalsmith-layouts` will render your layouts. So as long as you include both plugins in your metalsmith build process it'll all be rendered.

Hope that explains it a little. Let me know if you have any questions!

**Comment by iansoper** [comment]
Ahh, I got it. it is working now. Thanks!

**Comment by ismay** [comment]
No problem! Feel free to ask if anything else comes up.
