### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by fizzydigital** [superwolff/metalsmith-layouts#29]
So I am trying to do partial views for my site, like so:

```
src/layouts/default.hbs
src/partials/footer.hbs
```

So I can use them like this:

```
<html>
...
	<body>
	
		<div class="container">{{{contents}}</div>
	
		{{>footer}}

	</body>
</html>
```

What can I do to make this work?

**Comment by ismay** [comment]
What I'd recommend is this folder structure:

```
./partials
./layouts
./src
```

You can then use these options:

```json
{
  "plugins": {
    "metalsmith-in-place": {
      "engine":"handlebars",
      "partials": {
        "footer": "partials/footer"
      }
    }
  }
}
```

Use layouts like you normally would (by specifying them in the front-matter, as outlined in the documentation). Let me know if that works for you!

**Comment by fizzydigital** [comment]
I've used the structure you suggested, moved both `layouts` and `partials` outside `src` and added the `partials` object to `metalsmith.json`, but I can't get it to work.

I have two files:

`layouts/default.html':

```
<!doctype html>
<html>

	<head>
	
		<title>{{title}}</title>
		<link href="css/style.css" rel="stylesheet">

	</head>
	
	<body>
	
		<div class="container">{{{contents}}}</div>

		{{>footer}}

	</body>

</html>
```

and `partials/footer.html`:

```
<footer>

	<div class="container">
		
		<p>{{site.copyright}}</p>

	</div>

</footer>
```

But the rendered HTML looks like this:

```

<!doctype html>
<html>

<head>

	<title>Test site</title>
	<link href="css/style.css" rel="stylesheet">

</head>

<body>

	<div class="container">
		<h1 id="just-a-test-heading">Just a test heading</h1>
		<p>Lorem ipsum sit dolor et amet.</p>
		<p><small>Written by Fizzy D</small></p>
	</div>

	partials/footer.html
</body>

</html>
```

Here's my `metalsmith.json`:

```
{
    "source": "src",
    "destination": "public",
    "plugins": {
        "metalsmith-less": {
            "pattern": "less/**/*.less"
        },
        "metalsmith-markdown": true,
        "metalsmith-metadata": {
            "site": "data/site.json"
        },
        "metalsmith-in-place": {
            "engine": "handlebars",
            "partials": {
                "footer": "partials/footer.html"
            }
        },
        "metalsmith-layouts": {
            "engine": "handlebars",
            "default": "default.html",
            "directory": "layouts",
            "pattern": "*.html"
        },
        "metalsmith-beautify": true,
        "metalsmith-ignore": [
            "less/*"
        ],
        "metalsmith-serve": {
            "verbose": true
        }
    }
}
```

**Comment by fizzydigital** [comment]
Just in case, here's my `index.md`:

```
---
title: Test site
---

# Just a test heading

Lorem ipsum sit dolor et amet.

<p><small>Written by {{site.author}}</small></p>
```

**Comment by ismay** [comment]
The partials object should be added to metalsmith-layouts, not metalsmith-in-place. That should fix it.

**Comment by fizzydigital** [comment]
Yup, it did!

One thing though: I had to put `partials` back inside `layouts` directory, because I was getting an error:

`Error: ENOENT, open '/Users/admin/Sites/metalsmith/layouts/partials/footer.html'`

**Comment by ismay** [comment]
Ah yes, that's right. The paths are relative to the `layouts` folder. If you want to move your partials outside of it, you can, just adjust your paths accordingly.

I'll close this, let me know if anything else comes up!

**Comment by fizzydigital** [comment]
Bump: On a side note - is there a way to make the populate the partials object using a globbing pattern?

**Comment by ismay** [comment]
There will be soon, I'm working on it as we speak :). It won't accept a glob, but will allow you to specify a folder which will be scanned for partials.

**Comment by fizzydigital** [comment]
Wicked! I have just started playing with Metalsmith, but so far my mind is blown! I mean - WOW! Thanks man!

**Comment by ismay** [comment]
:) No problem, happy to help!

**Comment by ismay** [comment]
@fizzydigital Checkout version 1.3.0 for the `partials` option: https://github.com/superwolff/metalsmith-layouts/releases/tag/1.3.0
