### ISSUE TITLE
Layouts not rendered at all!

### ISSUE THREAD

**Issue by gabeno** [superwolff/metalsmith-layouts#34]
Here is my code:

__src/index.md__
```md
---
layout: layout.hbs
title: Test Article
---
  
### Test Article
Some content will go here...
```

__layouts/layout.hbs__
```html
!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>{{ title }}</title>
    </head>
    <body>
        {{> header }}
        {{{ contents }}}
        <p>Default Layout</p>
    </body>
</html>
```

__partials/header.hbs__
```html
<header>Header Content</header>
```

__build.js__
```js
var Metalsmith = require('metalsmith'),
    layouts  = require('metalsmith-layouts'),
    markdown   = require('metalsmith-markdown');

Metalsmith(__dirname)
    .use(markdown())
    .use(layouts({
        engine: 'handlebars',
        pattern: '*.hbs',
        partials: {
            'header': 'partials/header'
        }
    }))
    .destination('./build')
    .build(function(err, files){
        if (err) {
            console.log(err);
        }
    });
```

When I run ```node build.js``` I get the following:

__build/index.html__
```html
<h3 id="test-article">Test Article</h3>
<p>Some content will go here...</p>
```

Anything I might be missing?

**Comment by ismay** [comment]
Probably because you're filtering by `*.hbs`.

I don't know if `metalsmith-markdown` changes the extension to `.html`, but neither `.md` nor `.html` will be picked up if you're filtering with `.hbs`.

You could use `metalsmith-branch` and `metalsmith-rename` like I'm doing here: https://github.com/superwolff/boilerplate-layouts/blob/master/build.js#L61 . Might help.

**Comment by gabeno** [comment]
> I don't know if metalsmith-markdown changes the extension to `.html`

It does spit out ```.html```

So I changed the pattern to `pattern: '*.html'` when I ran it I got the error:

```bash
{ [Error: ENOENT: no such file or directory, open '.../layouts/partials/header.hbs']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.../layouts/partials/header.hbs' }
```

which I resolved by moving my ```partials/header.hbs``` into the __layouts__ folder.

On the other hand, declaring ```partials: 'partials'``` and letting the __partials__ sit in the root dir also works.

Which of the two approaches is optimal?

**Comment by ismay** [comment]
I think you're misunderstanding what the `pattern` option does. If you specify a pattern, it only processes files that match the pattern. Otherwise it processes everything. So only use it if you want to exclude files from being processed.

This is what I'd recommend (because I don't know if you have other filetypes in your buildchain, otherwise you can leave the pattern option out):

```javascript
var Metalsmith = require('metalsmith'),
    layouts  = require('metalsmith-layouts'),
    markdown   = require('metalsmith-markdown');

Metalsmith(__dirname)
    .use(markdown())
    .use(layouts({
        engine: 'handlebars',
        pattern: '*.html',
        partials: 'partials'
    }))
    .destination('./build')
    .build(function(err, files){
        if (err) {
            console.log(err);
        }
    });
```

__src/index.md__
```md
---
layout: layout.html
title: Test Article
---
  
### Test Article
Some content will go here...
```

__layouts/layout.html__
```html
!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>{{ title }}</title>
    </head>
    <body>
        {{> header }}
        {{{ contents }}}
        <p>Default Layout</p>
    </body>
</html>
```

__partials/header.html__
```html
<header>Header Content</header>
```

**Comment by gabeno** [comment]
I have the pattern included because it tries to process css files, for instance, that lie within the __src__ directory. I am using [this](http://www.robinthrift.com/posts/metalsmith-part-1-setting-up-the-forge/) directory structure.

**Comment by ismay** [comment]
Ok, then you can use my example and keep the pattern. Let me know if that solves it.

**Comment by ismay** [comment]
I'll assume that did, let me know if you have other questions!

**Comment by wdmtech** [comment]
Just adding this as the url @ismay posted has changed to

https://github.com/superwolff/metalsmith-boilerplates
