### ISSUE TITLE
No layout specified for ...

### ISSUE THREAD

**Issue by eoneill** [superwolff/metalsmith-layouts#35]
Starting with `v1.3.0`, metalsmith-layouts now requires a `layout` in the front matter.

This introduces a breaking change from `v1.2.1`, which would warrant a major version bump.

That said, it's unclear why this is desired behavior. Shouldn't it just ignore files without a `layout`?

I've worked around the immediate issue by setting...
```js
...
default: "empty.hbt"
```
and in `empty.hbt` I just do...
```handlebars
{{{ contents }}}
```
But this feels like an unnecessary hack.

**Comment by ismay** [comment]
I might have overlooked something, but it always required either a `default` layout, or a layout to be specified in the front-matter. Since this wasn't explicitly documented anywhere, and it just threw a `path` related error when both these were missing, I thought I'd make this a little more obvious. So there shouldn't be any changes in the underlying behaviour.

Are you sure you didn't encounter this with previous versions?

**Comment by ismay** [comment]
> Shouldn't it just ignore files without a layout?

I think it doesn't by design (this decision was made for metalsmith-templates), since that's its only purpose. If you want to ignore files the `pattern` option is meant for that.

**Comment by gregrafferty** [comment]
I've just been hit with the same issue. Was installing my project from scratch on a colleague's machine. We have a number of pages that don't get used individually but are collated into a parent page, hence the lack of a template at the individual level. This stopped working with the last update and we've had to add in an empty template and reference to it in each of the files.

**Comment by ismay** [comment]
Ok, then I've probably overlooked something. I'll take a look and refactor this to a non-breaking change. @gregrafferty Which version were you using before the update?

**Comment by ismay** [comment]
I still think it's weird that you're both encountering this now, when this line https://github.com/superwolff/metalsmith-layouts/blob/master/lib/index.js#L118 has been in this plugin for a long time. Longer than the explicit error message. And it results in an error on non-specified layouts just the same.

@eoneill Could you give me your latest working version number of `metalsmith-layouts` as well? A link to a repo that demonstrates `metalsmith-layouts` working in the manner you described (without errors, and without layouts specified for each matched file) would be great.

**Comment by eoneill** [comment]
Sorry for the slow response.

Here's my repo:
https://github.com/eoneill/restylecss.com

If you look at this revision, you can reproduce the issue:
https://github.com/eoneill/restylecss.com/tree/a96e0076f53bc38b231024ac4ad3f0c3be6ee84c

At this revision, `metalsmith-layouts` is pegged to `1.2.1`

You can successfully build using `gulp build`.

Now to reproduce the issue, bump `metalsmith-layouts` to `1.3.1` and you'll see the error.

The next commit uses my workaround to unblock this:
https://github.com/eoneill/restylecss.com/commit/43808e69a97fcc99b937c52dc1d9590e91d4b85a

It might be that I got lucky with the way handlebars is working under the hood and this wasn't an intended behavior.

Thanks for looking into this!

**Comment by rstacruz** [comment]
I, too, would really like the idea of ignoring files without layouts. It seems limiting to only have `pattern` as the way to specify which files will be needing layouts. I'll probably have `pattern` set to `*.html` (which is reasonable), but I'd also like to have some HTML files exist without layouts.

**Comment by rstacruz** [comment]
Could this perhaps be a better way to handle it? ([source](https://github.com/superwolff/metalsmith-layouts/blob/1.3.1/lib/index.js#L110-L113))


```js
      // Require a default or a layout to be specified for each file
      if(!data.layout && !def) {
    -   throw new Error('No layout specified for ' + file);
    +   return done();
      }
```

**Comment by ismay** [comment]
@eoneill np, thanks for the link. 

@rstacruz yeah, that makes sense. Regardless of whether `metalsmith-layouts` would or wouldn't trip over files without a layout before `1.3.1`, there's no point in trying to process files without a specified layout.

**Comment by ismay** [comment]
Published as 1.4.0 since this shouldn't be a breaking change.

**Comment by eoneill** [comment]
Awesome, thanks for the quick turnaround on this!

Confirmed it working with the previous behavior.

**Comment by ismay** [comment]
:+1: Thanks for the confirmation!
