### ISSUE TITLE
document partials

### ISSUE THREAD

**Issue by rstacruz** [superwolff/metalsmith-layouts#36]
It seems partials support is now available! Would be nice to know how they're meant to work, along with some examples. Eg,

* Will they work for indented languages like Jade?
* Will I be able to access page metadata from partials?
* Can I pass local variables to partials (`{{> profile name="John Smith"}}`)?
* etc...

**Comment by ismay** [comment]
See here: https://github.com/superwolff/metalsmith-layouts#partials. It is just an easy way to register partials with consolidate.

They'll work for all languages that consolidate has implemented partials for (as far as I know jade doesn't use partials but includes and extends, which don't need to be registered). See consolidate source, and the `readPartials` method.

Other than that you'll have all the partial functionality that comes with the engine you're using (so variables for handlebars, etc.).
