### ISSUE TITLE
Nested `src` directories not finding layouts

### ISSUE THREAD

**Issue by radiovisual** [superwolff/metalsmith-layouts#40]
I have an issue where all my root-level handlebars templates are rendering perfectly, but any content files nested within directories are not linking with the appropriate layouts. 

For example, consider this folder structure:

```
layouts/
    index.hbs
    subpage.hbs

src/
    subsection01/
        index.hbs    <--- layout:subpage.hbs  DOES NOT FIND TEMPLATE
    index.hbs        <--- layout:index.hbs    FINDS TEMPLATE
```

So after I run `metalsmith.build()`, The url `/index.html` renders perfectly and finds the template in `layouts/index.hbs`, but the url `/subsection01/index.html` only loads the contents of `src/subsection01/index.hbs` and does not find the template `layouts/subpage.hbs`

Is there something obvious that I am missing here? I feel like the solution is simple and staring me in the face, but I can't see it now. 

If you want to see a live example, [I have a github repository with a starter project](https://github.com/radiovisual/metalsmith-boilerplate) that currently demonstrates the exact problem.  If you install my boilerplate project and run it, as soon as you click on any of the "Subsection" links in the navigation you will see what I am talking about. 

I would appreciate the help!

**Comment by ismay** [comment]
I think it's [this line](https://github.com/radiovisual/metalsmith-boilerplate/blob/master/index.js#L50), it should be `**/*.hbs`. Right now you're only passing top-level .hbs files through the branch. The `**` ensures that subdirectories are also included.

Let me know if that does it!

**Comment by radiovisual** [comment]
:smiley: That did it! I knew it was going to be something simple. Thanks @ismay!

**Comment by ismay** [comment]
:+1: no problem!
