### ISSUE TITLE
'layout' and 'template' meta data variable

### ISSUE THREAD

**Issue by saneef** [superwolff/metalsmith-layouts#42]
To make metalsmith-layout, a drop-in replacement for the deprecated metalsmith-templates, is it possible to use `template` meta data in addition to the existing `layout`?

It also, helps metalsmith-layout to work seamless with other plugins like 'metalsmith-pagination',…

**Comment by ismay** [comment]
I don't think that should be a responsibility of metalsmith-layouts. However you could write a plugin that modifies all `template` keys in the front-matter to `layout`. I'd have no problem linking to it in the readme.
