### ISSUE TITLE
Layouts & partials folders created in build folder

### ISSUE THREAD

**Issue by MarkusPint** [superwolff/metalsmith-layouts#47]
Is this intended behaviour? Any hints on how to avoid this would be great.

**Comment by ismay** [comment]
No it isn't. You're probably putting them in your source (`src`) folder. Which means metalsmith will copy them to your build folder.

See the [tests](https://github.com/superwolff/metalsmith-layouts/tree/master/test/fixtures) for the recommended layout.

**Comment by MarkusPint** [comment]
Aha! Got it now. Thanks a bunch!

**Comment by ismay** [comment]
No problem :+1:
