### ISSUE TITLE
Metalsmith · [metalsmith-sass] Error: invalid top-level expression -> :1:1

### ISSUE THREAD

**Issue by karneaud** [superwolff/metalsmith-layouts#49]
My sass file has 

`@import './components/bower_components/sassarch/sass/style';`

My metal script jason has

`"metalsmith-sass":
    {
        "files":["*.css"],
        "includePaths":["app/components/bower_components/sassarch/sass"],
        "outputDir":"css",
        "watch":"*.scss",
        "indentedSyntax": false
    },`
and when I run the metalsmith script I get

> Metalsmith · [metalsmith-sass] Error: invalid top-level expression -> main.scss:1:1

I'm not sure what is wrong though...I am new to metalsmith and sass
Any thoughts?

**Comment by ismay** [comment]
You've got the wrong repository, try it at: https://github.com/stevenschobert/metalsmith-sass

**Comment by karneaud** [comment]
sunnufah

**Comment by karneaud** [comment]
see this though https://github.com/stevenschobert/metalsmith-sass/issues/29 it refers to your plugin

**Comment by ismay** [comment]
Doesn't seem to be a metalsmith-layouts related issue.
