### ISSUE TITLE
Support Template Inheritance

### ISSUE THREAD

**Issue by dstaley** [superwolff/metalsmith-layouts#50]
It'd be awesome if a layout file could extend another layout. For example I could have a `base.html` layout that has the opening `<html>` tag, `<head>` partial, and `<body>` tags. Then, I could have a `post.html` layout that has `layout: base.html` in it's frontmatter. Finally I could have a page in my `src` directory that has `layout: post.html`, which would get contents from `post.html` and `base.html`. This is essentially the same things as [this previous feature request](https://github.com/segmentio/metalsmith-templates/issues/43) on the metalsmith-template repo.

**Comment by ismay** [comment]
Yeah extending layouts can be very useful. But metalsmith-layouts is meant to be a shim for languages that don't support extending. If you want to use extends I recommend https://github.com/superwolff/metalsmith-in-place, with a language like jade or swig. Or you could even try using such a language with metalsmith layouts.

**Comment by ismay** [comment]
That's already possible, you just need to use a language that supports extends, like swig. Check out https://github.com/superwolff/boilerplate-layouts/tree/extends, it demonstrates the use of extends and includes with metalsmith-layouts.
