### ISSUE TITLE
Not being able to render jade blocks

### ISSUE THREAD

**Issue by v3rt1go** [superwolff/metalsmith-layouts#51]
Hi guys,

I'm using jade as the template engine and blocks are not rendering from the layout file.

I have the following file structure:

src/post.md - the file that is going to be built, which contains:
``` markdown
    ---
    layout: post.jade
    title: The title goes here
    ---
    # Hello World!
```
layouts/homepage.jade - this contains various main, footer and head blocks
layouts/post.jade - this is the main post template that contains
layouts/head.jade - the head block

``` jade
extends homepage

block main
  #content!= contents
```

and partials/footer.jade with:
``` jade
extends homepage

block footer
  #footer
    p footer content here
```

My build.js file looks like this:

``` javascript
var Metalsmith = require('metalsmith'),
  markdown = require('metalsmith-markdown'),
  layouts = require('metalsmith-layouts'),
  inPlace = require('metalsmith-in-place');

Metalsmith(__dirname)
  .use(markdown())
  .use(layouts({
    engine: 'jade',
    directory: 'layouts',
    partials: 'partials'
  }))
  .build(function(err) {
    if (err) throw err;
  });
```

If, on my post.md file I set the layout to homepage.jade NONE of the blocks are rendering.
While using post.jade as layout ONLY the main block is rendering inside of the homepage layout (extends seem to work).
If I use `block main` in any other jade file, that will not render either.

Could you please give me some feedback on this issue. It was previously working with metalsmith-templates ...

Cheers!

**Comment by ismay** [comment]
No problem, can you create a reduced test case that demonstrates the problem (and push it to a github repo)? That'll make it easier for me to take a look at it.

**Comment by v3rt1go** [comment]
Hi @ismay 

Thanks for your reply.
I've created a github repo to showcase the issue, and added the details in the readme file.

[https://github.com/v3rt1go/metalsmith-layout-jade](https://github.com/v3rt1go/metalsmith-layout-jad)

Thanks for your help!

**Comment by ismay** [comment]
np :+1:
