### ISSUE TITLE
Pattern Check with Multimatch

### ISSUE THREAD

**Issue by dacodekid** [superwolff/metalsmith-layouts#53]
Hi,

Just found a bug in this line.  https://github.com/superwolff/metalsmith-layouts/blob/master/lib/helpers/check.js#L29

This needs to be changed to ```if (pattern && !match(file, pattern, {matchBase: true})[0]) {``` in order to escape ```/``` from the ```file``` name.  Please see this https://github.com/sindresorhus/multimatch/blob/master/test.js#L202-L209

**Comment by dacodekid** [comment]
Created a pull request here https://github.com/superwolff/metalsmith-layouts/pull/54

**Comment by ismay** [comment]
Closed from #54
