### ISSUE TITLE
Have layout for a layout

### ISSUE THREAD

**Issue by soswow** [superwolff/metalsmith-layouts#57]
Is there a way to define a layout for a layout?
For example I have a "layouts/post.html":
```html
---
layout: default
---
<div class="post">
  <h1 class="post-title">{{ title }}</h1>
  <span class="post-date">{{ date|date('d.m.Y') }}</span>
  {{ contents|safe }}
</div>
```
and I have `layouts/default.html`:
```html
<!DOCTYPE html>
<html lang="en-us">
<body>
<div class="container content">
        {{ contents|safe }}
</div>
</body>
```
and `src/some-post.md`:
```markdown
---
title: First Post
date: 2012-08-20
layout: post.html
---

Some testing here
```
?

(I am trying to adopt jekyll theme)

**Comment by ismay** [comment]
Yeah that's possible, it's called an extend and is supported by the Swig templating language amongst others. See here: https://github.com/superwolff/metalsmith-boilerplates/tree/layouts/extends for an example.

**Comment by aliok** [comment]
@ismay Could you also point an example with Handlebars?

**Comment by ismay** [comment]
@aliok Unfortunately not, handlebars doesn't natively support extends.
