### ISSUE TITLE
liquid filename bug

### ISSUE THREAD

**Issue by soswow** [superwolff/metalsmith-layouts#59]
```javascript
var basename = path.basename(name);
var extname = path.extname(name) || '.liquid';
var filename = path.join(includeDir, basename + extname);

name === "default.html" // Input
basename === "default.html"
extname === ".html"
filename === "default.html.html" // variable used to fetch the file from file system.
```

**Comment by ismay** [comment]
Could you elaborate? What exactly is the issue?

**Comment by soswow** [comment]
ok. I was sure that would be enough to indicate a problem.
```
{% extends "default.html" %}
```
fails with exception
```
Fatal error: ENOENT, open '/Users/xxxxx/Documents/blog/default.html.html'
```

**Comment by soswow** [comment]
oops. sorry, it's in consolidate code base (facepalm)

**Comment by soswow** [comment]
Looks like consolidate is dead, though =(

**Comment by ismay** [comment]
I don't know, the maintainer's active, and it still works well. I assume that it'll be deprecated if it's unmaintained. But who knows.

**Comment by soswow** [comment]
Oh, indeed it does. Looks like I'll fix it myself
