### ISSUE TITLE
How do you configure templating engines?

### ISSUE THREAD

**Issue by Rowno** [superwolff/metalsmith-layouts#6]
Nunjucks needs to be able to be configured to disable it's builtin watcher and set the template directory for extending. This could be solved by exposing the [consolidate template engines](https://github.com/tj/consolidate.js#template-engine-instances).

See segmentio/metalsmith-templates#55

**Comment by grancalavera** [comment]
I'm using nunjucks, and I'm facing the same issue. I found you can configure nunjucks and add filters globally:

```
nunjucks
  .configure({watch: false})
  .addFilter('stretch', function(str) {
    return str.split('').map(function(char) {
      var stretched = '', i = 0
      for (i; i < 5; i++) { stretched += char }
      return stretched
    }).join('').toLowerCase()
  })
```

Then you can use the filter normally in your templates:
```
{{ title|stretch }}
```

**Comment by ismay** [comment]
Sorry for the late reply, I've been a little busy. But yeah, as @grancalavera said, you can configure a global instance of the templating engine to solve this.

I'm doing something similar [here](https://github.com/superwolff/cape/blob/master/gulp/util/gulpsmith.js), where I'm instantiating handlebars and passing it some partials, to be used later in metalsmith. Let me know if that solves it for you!

**Comment by Rowno** [comment]
Thanks, I ended up using Swig and configuring it globally using `swig.setDefaults({ cache: false });`. But it's likely that not all templating engines support global config.

**Comment by ismay** [comment]
@Rowno Yeah that could be, I'll check it out. It needs to at least be documented, because I ran into this myself as well.

**Comment by ismay** [comment]
Related: https://github.com/segmentio/metalsmith-templates/issues/23

**Comment by ismay** [comment]
@Rowno , So depending on the outcome of this issue: https://github.com/tj/consolidate.js/issues/203, it might indeed be a good idea to expose the `consolidate.requires` object.

**Comment by micahgodbolt** [comment]
@ismay your link of https://github.com/superwolff/cape/blob/master/gulp/util/gulpsmith.js 404s now. I'm still struggling with nunjucks and extending directory. Is there a new home for that file?

**Comment by micahgodbolt** [comment]
Ah! Finally found it. The directory has to be set like this:

```
var nunjucks = require('nunjucks');
nunjucks.configure('./templates', {watch: false})
```
