### ISSUE TITLE
Does Nunjucks actually work with metalsmith-layouts?

### ISSUE THREAD

**Issue by micahgodbolt** [superwolff/metalsmith-layouts#62]
Has anyone successfully got nunjucks working with metalsmith-layouts? I'm quite interested in using them after finding out Swig was no longer being maintained, but I am unable to specify the folder for includes or extends.

There was some discussion on #43 about this same issue, but it was closed without giving any examples.

**Comment by micahgodbolt** [comment]
Ok! Here we go. I finally found a working solution. It just takes some external settings like so:

```
var nunjucks = require('nunjucks');
nunjucks.configure('./templates', {watch: false})
```

**Comment by ismay** [comment]
Cool, thanks for sharing. So does this work without issue? Because I've worked with nunjucks, but I remember the whole process being very fiddly.

**Comment by micahgodbolt** [comment]
@ismay yes, this allows @extends and @imports to work from the specified directory

**Comment by ismay** [comment]
That's good to know, I'll add it to the documentation

**Comment by aeichepdx** [comment]
I know this is closed, but I wanted to add a quick piece of information for anyone who might be googling for help. If you need to provide separate template and partial directories, you can pass an array to the nunjucks.configure call, like so:

```
var nunjucks = require('nunjucks');
nunjucks.configure(['./_layouts','./_partials'], {watch: false});
```

This is useful if you're running into confusing "unknown path" errors like I was, when the template very obviously existed.
```
node build
{ [Template render error: (unknown path)
  Error: template not found: /home/user/metalsmith_build/_partials/head.html] name: 'Template render error' }

```

**Comment by doodzik** [comment]
@aeichepdx Thanks for adding this bit of info.

**Comment by Andersos** [comment]
I'm trying to get Nunjucks to work with Metalsmith but where do I put this code:

```
var nunjucks = require('nunjucks');
nunjucks.configure('./templates', {watch: false})
```

**Comment by slavafomin** [comment]
I've written a small article on [how to make Nunjucks to work with Metalsmith](https://medium.com/@slavafomin/making-metalsmith-to-work-with-nunjucks-a67a74c3e73d).

In it, I'm using `in-place` plugin instead of `layouts`, but still, I hope it could save you some time.
