### ISSUE TITLE
Adding custom helpers

### ISSUE THREAD

**Issue by Ghosh** [superwolff/metalsmith-layouts#63]
Is there any way to add custom helpers to handlebars?

I basically want to use the handlebars-layouts library. I cannot figure out how to register the helpers. 

I tried registering them individually using the metalsmith-register-helpers plugin, but that doesn't seem to work.

**Comment by ismay** [comment]
> Is there any way to add custom helpers to handlebars?

There is, the method I used is just the method that's outlined in the handlebars-layouts readme:

```
var handlebars = require('handlebars'),
    layouts = require('handlebars-layouts');

handlebars.registerHelper(layouts(handlebars));
```

Since metalsmith should use the global handlebars instance, this should be sufficient. Let me know if you have any other questions!

**Comment by Ghosh** [comment]
Thanks for the prompt reply. I was using the metalsmith.json file to configure till now. Seems like I will have to move to the javascript method now.

Thanks!

**Comment by ismay** [comment]
Yeah the javascript api is a lot more flexible. Good luck!

**Comment by AlexZeitler** [comment]
How do I use the handlebar-layouts with metalsmith layouts?

**Comment by AlexZeitler** [comment]
Got it working using ```metalsmith-register-helpers```

**Comment by Ghosh** [comment]
@ismay While it is working the way you mentioned using the javascript api in a stand alone build.js file, the metalsmith-layouts doesn't seem to picking up the global handlebar instance when used in a gulp file using the `gulpsmith` plugin.

Any thoughts on that?

**Comment by ismay** [comment]
Hmm ok. I used to do just that, so it should be possible. But other than that, depending on it being globally available isn't exactly pretty anyway. Issue #18 was meant to address that, but I'm rather busy atm., so haven't had any time to fix it yet.

A pr would be welcome :).
