### ISSUE TITLE
Update to consolidate 0.14

### ISSUE THREAD

**Issue by spiffytech** [superwolff/metalsmith-layouts#66]
v0.14 includes support for passing Lodash options through to the Lodash renderer. That would be _super_ helpful for me.

Nothing in the list of commits between v0.13.1 and v14 sounds (to me, at least) like it would break for metalsmith-layouts.

**Comment by ismay** [comment]
All tests are passing with 0.14.0 and I don't see any breaking changes either. Published on npm as 1.4.3, thanks for the heads up :+1: !

**Comment by spiffytech** [comment]
Updated my project and confirmed metalsmith-layouts, and the updated Lodash support, are working. 

Thanks for the fast response!

**Comment by ismay** [comment]
Cool! :+1:
