### ISSUE TITLE
Support multiple template directories?

### ISSUE THREAD

**Issue by madeofpeople** [superwolff/metalsmith-layouts#69]
In certain projects
It would be useful to pass an array of directories (or better yet blob patterns) to treat as templates.

Specifically in the case of styleguide generation.

**Comment by ismay** [comment]
Sounds like a good idea, an array of globs would be nice. [glob](https://www.npmjs.com/package/glob) could be useful, but doesn't seem to support arrays of patterns. But it should be doable.

I'm pretty busy atm., but wouldn't mind adding this if I can find some time. Don't know if you have time for a PR? It would require some refactoring and at least one new test.

**Comment by madeofpeople** [comment]
I think I do in fact have some time. 
I will take a stab at it.

**Comment by doodzik** [comment]
can't you just call the layout function multiple times in the build process? Seems to me a little bit like over engineering.

**Comment by ismay** [comment]
That's true, and it would be more maintainable to keep it as is. Unless there's a common use-case that can't be addressed with the current functionality (or another plugin).

How exactly do you intend to use this for styleguide generation @madeofpeople? Would it not be better to use multiple calls, or metalsmith-in-place?

**Comment by doodzik** [comment]
I'm going to close this until we hear back.

**Comment by mlholt03** [comment]
It looks like the recommended solution (call layout multiple times) is not functioning.   If I have the following folder structure:
* project_root
  * content  
    * index.md
    * _index.md
  * layouts
    *sample.jade
  * layouts2
    * sample2.jade

And then implement the suggested solution below: 
    .use(layouts({
      engine: 'jade',
      pattern: '**/*.md',
      directory: options.templatesDir,
      rename: true
    }))
    .use(layouts({
      engine: 'jade',
      pattern: '**/_*.md',
      directory: './layouts2',
      rename: true
    }))

The following error is generated when trying to build: "ENOENT: no such file or directory, open 'project_root\layouts\sample2.jade'"
