### ISSUE TITLE
wrong layouts directory with nunjucs

### ISSUE THREAD

**Issue by tiagoantao** [superwolff/metalsmith-layouts#70]
I have a standard

{{ extends "base.html" }}

entry on my nunjucs templates.

But when I run the plugin it will not read the base.html from the layouts/ directory but from the root of my project:

```
/
  base.html <-- used
  /layouts
    base.html <-- ignored

```

**Comment by ismay** [comment]
Yeah that differs from engine to engine. But you should be able to set the basepath for your nunjucks instance. Let me know if that doesn't work.
