### ISSUE TITLE
Fix hound linting

### ISSUE THREAD

**Issue by ismay** [superwolff/metalsmith-layouts#77]
See: https://github.com/houndci/hound/issues/1081

**Comment by doodzik** [comment]
did you get an answer from them?

**Comment by ismay** [comment]
Yeah I did, but I didn't find what caused the bug. In the end I decided to go with linting through travis (which I'm currently only using [here](https://github.com/ismay/ismay.github.io/blob/development/.travis.yml#L11)), as I was already using travis and it's a little more flexible.

What do you think? We could close this and implement linting through travis instead of hound.

**Comment by doodzik** [comment]
I think that it would make sense. Just using with what works best at the moment 👍
