### ISSUE TITLE
Trouble resolving path to partial

### ISSUE THREAD

**Issue by tschaub** [superwolff/metalsmith-layouts#78]
I've run into some trouble using partials when a layout is in a subdirectory of the primary `layouts` directory.  For example, this directory structure causes problems:

```
src/
  index.html
layouts/
  nested/
    layout.html
partials/
  partial.html
```

Using this `metalsmith.json`

```json
{
  "plugins": {
    "metalsmith-layouts": {
      "engine": "handlebars",
      "partials": "partials"
    }
  }
}
```

If `src/index.html` has `layout: nested/layout.html` and `layouts/nested/layout.html` refers to `{{> partial}}`, running `metalsmith` generates this error:

```
ENOENT: no such file or directory, open '/path/to/project/layouts/partials/partial.html'
```

This is using `metalsmith-layouts@1.6.4`.  Additional details and a repo that demonstrates the problem are here: https://github.com/tschaub/test-metalsmith-layouts

**Comment by GRUBES** [comment]
@tschaub Did you ever resolve this? I am running into a similar problem, except my partial is the one in the subdirectory.

My plugin configuration is the same.

My directory structure is:

```
src/
  index.html
layouts/
  index.html
partials/
  home/
    header.html
```

My `index.html` has frontmatter `layout: index.html`, which references `{{> home/header }}`. Upon build, I get

```
Metalsmith - The partial home/header could not be found
```

Looking at the source of this library, it appears to read the `partials` directory recursively, so I thought my folder structure would be OK.

**Comment by GRUBES** [comment]
I've found the reason my partials are not found. I am running on Windows, so my partial gets registered as `home\header` instead of `home/header`.

**Comment by doodzik** [comment]
@tschaub did you resolve this issue or should I look into it?

Going to reopen if I hear back from you and it isn't resolved yet.

**Comment by jin-jianfeng** [comment]
@doodzik - seem it is not resolved.

**Comment by ismay** [comment]
@jin-jianfeng Thanks for the report. Unfortunately we'll need more details to do anything about it. Please submit a PR with a failing test so that we'll know where it's failing. Thanks!
