### ISSUE TITLE
Handlebars issue with <!DOCTYPE html>

### ISSUE THREAD

**Issue by diroru** [superwolff/metalsmith-layouts#80]
Hello,
not sure if it is a metalsmith or handlebars issue. I am new to (and excited by!) metalsmith and trying to get my setup up and running. However, with `handlebars` version `^4.0.5` i just can't get my doctype declaration _not_ to be escaped.

In my `build.js` i have (as a desperate measure):

```
…
var handlebars  = require('handlebars');

handlebars.registerHelper('doctype', function() {
  return new handlebars.SafeString('<!DOCTYPE html>');
});
…
```

in my `header.hbt` i have:
```
{{{doctype}}}
<html>
<head>
  <title>{{title}}</title>
</head>
``` 
and as an output in the index.html i have:
```
<p>&lt;!DOCTYPE html&gt;</p>
…
```
Any ideas what could be going wrong?

Thanks a lot in advance!
Cheers,
dimitar

**Comment by diroru** [comment]
Seems to be an issue with a plugin (invocation order). Will reopen it, if i have a more specific handle on the matter. Sorry for the pollution.

**Comment by ismay** [comment]
@diroru No problem! Just so others running into this issue know, do you know which plugin was causing the trouble?

Also, why are you using a helper for the doctype and not a partial? Just for testing purposes? Because otherwise I'd say that a partial would be more suited, if it's just static html you're outputting.

**Comment by diroru** [comment]
@ismay Thanks for the response! I ran some tests and it seems i made a novice mistake: was calling `use(layouts(…))` _before_ calling `use(markdown(…))` . Yes, the helper was merely used in the hope of resolving the issue.

Cheers!

**Comment by ismay** [comment]
Ah ok. Thanks for the reply!
