### ISSUE TITLE
Not able to render jade page within jade layout

### ISSUE THREAD

**Issue by DusanMilko** [superwolff/metalsmith-layouts#85]
my page:
```
---
layout: default.jade
---
div#hello Text
```

my layout:
```
doctype html
html(lang="en")
	body#top
		= contents
```

result:
```
<!DOCTYPE html>
<html lang="en">
<body id="top">
div#hello Text
</body>
</html>
```

expected result:
```
<!DOCTYPE html>
<html lang="en">
<body id="top">
<div id="hello">
Text
</div>
</body>
</html>
```

**Comment by doodzik** [comment]
The content of 'my page' is passed to the layout as a variable and won't be interpreted as a jade markup.
You want to convert your file 'my page' before it is passed to the layout function.

**Comment by ismay** [comment]
Exactly, you can use [metalsmith-in-place](https://github.com/superwolff/metalsmith-in-place) for that.
