### ISSUE TITLE
How to set preventIndent?

### ISSUE THREAD

**Issue by julmot** [superwolff/metalsmith-layouts#86]
I need to set the compile option `preventIndent` of handlebars. I don't see an option to set compile settings.

**Comment by julmot** [comment]
Seems like just setting it directly works. For example:
```javascript
    .use(templates({
        "directory": templatesDir,
        "partials": templatePartialsDir,
        "engine": "handlebars",
        "preventIndent": true
    }))
```

However, in my opinion this should definitely be documented.

**Comment by ismay** [comment]
It is documented, see here: https://github.com/superwolff/metalsmith-layouts#consolidate. `preventIndent` is not a metalsmith-layouts option, but something that gets passed on to consolidate.
