### ISSUE TITLE
using 2 layout engines?

### ISSUE THREAD

**Issue by rstacruz** [superwolff/metalsmith-layouts#9]
is using handlebars and jade at the same time a supported use case?

```js
ms = new Metalsmith(dir)
  .use(require('metalsmith-layouts')({ engine: 'handlebars' }))
  .use(require('metalsmith-layouts')({ engine: 'jade' }))
```

```yaml
---
# file1.html
layout: handlebars.html
---
```

```yaml
---
# file2.html
layout: nested.jade
---
```

**Comment by rstacruz** [comment]
i dont think this will work, but perhaps it should be. it shouldn't be difficult, maybe by using a `layoutPattern`:

```js
ms = new Metalsmith(dir)
  .use(require('metalsmith-layouts')({ engine: 'handlebars', layoutPattern: /\.html/ }))
```

a `pattern` option is already supported, but it checks the main file's pattern, not the layout.

**Comment by ismay** [comment]
This should already be possible. Just use a pattern to filter what you want to compile, and pass `metalsmith-layouts` the relevant options. Check [this test](https://github.com/superwolff/metalsmith-layouts/blob/master/test/index.js#L28) for an example.

Let me know if that works out.

**Comment by rstacruz** [comment]
indeed it should work, but your pattern is checking your source files, so you'll need to define a strict pattern for it. For instance, in this setup:

```html
<!-- src/about.html -->
---
layout: article.jade
---
...
```

```html
<!-- src/contact.html -->
---
layout: default.html
---
...
```

...it doesn't auto-detect that the first file needs a `.jade` template, and the second needs an `.html` template and act accordingly. for this to work, youll need to hard-code your files according to what templates they need, like `engine: 'jade', pattern: 'about.html'` which is pretty strange.

**Comment by ismay** [comment]
Ah, I see what you mean. I've always used metalsmith with gulp, so I always handled my extensions through gulp, which allowed me to filter `.hbs`, `.swig`, etc.

Maybe it'd be an idea to filter by extension, and have metalsmith-templates accept an output extension option. With `.html` as the default. Not sure whether that would be wise though.

Related: https://github.com/segmentio/metalsmith-templates/issues/6

**Comment by rstacruz** [comment]
what do you think of this suggestion here? https://github.com/superwolff/metalsmith-layouts/issues/9#issuecomment-122053744

**Comment by ismay** [comment]
Well, in my opinion a file extension is already something that identifies templating syntax. So I'd prefer that over a more custom solution myself.

**Comment by rstacruz** [comment]
hmm.. that may be true for things like `.jade`, but there might be different cases for, say, `.html` (that can be using handlebars or swig or hogan), or templating engines that don't have de-facto extensions (like react, ractive, haml-coffee).

**Comment by ismay** [comment]
Yeah, that's true. Wouldn't something like https://github.com/treygriffith/metalsmith-include do what you're trying to do here?

**Comment by rstacruz** [comment]
I'm curious actually because this is a pretty common pattern in Jekyll sites I've done. It'd probably start off as liquid .html's and eventually migrate slowly into .haml's with both co-existing. there may be .html's using .haml's as templates and vice versa.

**Comment by ismay** [comment]
Ok I see. And what about this:

> Wouldn't something like https://github.com/treygriffith/metalsmith-include do what you're trying to do here? It originated in a similar issue.

**Comment by ismay** [comment]
Using two layout engines should be fine, but you'll have to differentiate between both syntaxes via file extensions (and filter with a `pattern`). Then you could optionally rename all files to .html with [metalsmith-rename](https://github.com/MoOx/metalsmith-rename).

I don't see a `layoutPattern` contributing anything extra to the solution as both source and layout can share the same extension, and thus would be similarly 'filterable'.

I think that filtering by pattern isn't an optimal solution, but since the use case probably isn't very common, it doesn't seem to be worth the added complexity for solving this problem. So I'll be closing this, but feel free to comment if anything should come up.
