### ISSUE TITLE
Support nested layouts

### ISSUE THREAD

**Issue by stereobooster** [superwolff/metalsmith-layouts#90]
see example of typical Jekyll theme https://github.com/rohanchandra/type-theme/blob/master/_layouts/page.html

`page.html` is layout which is based on layout (`default.htlm`) itself.

**Comment by ismay** [comment]
Duplicate of https://github.com/superwolff/metalsmith-layouts/issues/57. See the solution provided there or alternatively, check out [this](https://github.com/superwolff/metalsmith-boilerplates/tree/in-place/complete) example.

**Comment by stereobooster** [comment]
This is not exactly what Im  looking for. Im looking way to use metalsmith as drop-in replacement for Jekyll. I do not want to edit Jekyll itself. As far as I see metalsmith can't handle this task so far. Thanks for response.

**Comment by ismay** [comment]
I understand, but it is not the intention of this project to be a drop-in replacement for jekyll. If you want to use this library you'll have to modify your code where necessary.

I don't even think you'll have to change that much btw., just take a look at the examples I linked to earlier.
